<?php

/*
 * This file is part of the swOptimizeRoutesPlugin package.
 *
 * (c) 2008 Thomas Rabaix <thomas.rabaix@soleoweb.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
require_once dirname(__FILE__).'/../bootstrap/unit.php';

$t = new lime_test(0, new lime_output_color());

// create 500 routes
$routes = array();
foreach(range(1, 500) as $num)
{
  $routes['route_'.$num] = new sfRoute('/path/'.$num);
}

// create output file TEST 1
// sf1.2 like, object instanciation
$data = array();
foreach($routes as $name => $r)
{
  $data[] = sprintf('\'%s\' => new sfRoute("/route/:id", array(), array("id" => "\d+")),', $name);
}

file_put_contents(
  dirname(__FILE__).'/../cache/test1.cache',
  sprintf(
    "<?php\n".
    "// auto-generated by sfRoutingConfigHandler\n".
    "// date: %s\nreturn array(\n%s\n);\n", date('Y/m/d H:i:s'), implode("\n", $data)
  )
);

// create output file TEST 3
//   array of object's serialization
$data = array();
foreach($routes as $name => $r)
{
  $data[] = sprintf('\'%s\' => new sfRoute("/route/:id", array(), array("id" => "\d+")),', $name);
}

file_put_contents(
  dirname(__FILE__).'/../cache/test2.cache',
  serialize($routes)
);

$data = array();
foreach($routes as $name => $route_instance)
{
  $options = array();
  if($route_instance instanceof sfObjectRoute)
  {
    $options['model'] = 'foo';
    $options['type'] = 'object';
  }

  $export = array(
    'route_class' => get_class($route_instance),
    'route_serialization' => $route_instance->serialize()
  );

  $data[] = sprintf('\'%s\' => %s,', $name, var_export($export, 1));
}

file_put_contents(
  dirname(__FILE__).'/../cache/test3.cache',
  sprintf(
    "<?php\n".
    "// auto-generated by swOptimizeRoutingConfigHandler\n".
    "// date: %s\nreturn array(\n%s\n);\n", date('Y/m/d H:i:s'), implode("\n", $data)
  )
);


// TEST 4
// an array, only possible with sf1.3 without any hack into the framework
$data = array();
foreach($routes as $name => $route_instance)
{
  $options = array();
  if($route_instance instanceof sfObjectRoute)
  {
    $options['model'] = 'foo';
    $options['type'] = 'object';
  }

  $export = array(
    'route_class' => get_class($route_instance),
    'route_serialization' => unserialize($route_instance->serialize())
  );

  $data[] = sprintf('\'%s\' => %s,', $name, var_export($export, 1));
}

file_put_contents(
  dirname(__FILE__).'/../cache/test4.cache',
  sprintf(
    "<?php\n".
    "// auto-generated by swOptimizeRoutingConfigHandler\n".
    "// date: %s\nreturn array(\n%s\n);\n", date('Y/m/d H:i:s'), implode("\n", $data)
  )
);